### PR TITLE
hu locale

### PR DESCRIPTION
**Pull request by ovari**
- corrected en locale spelling mistakes
- updated strings for better consistency with Thunderbird strings https://transvision.mozfr.org/
- updated quotation marks for languages https://en.wikipedia.org/wiki/Quotation_mark#Summary_table
- added hu locale (Hungarian - magyar)
- updated locales to Thunderbird standard, as shown in "Source Locale" and "Target Locale" in https://transvision.mozfr.org
- few additional updates and fixes

### CODE REVIEW

**Comment by cleidigh** [comment]
@ovari 
Wow, much more than just adding Hungarian.  Thanks for the edits and cleanup.  I've been so focused on the startup I have done no scrubbing.

Couple of clarifications:
- you changed keyboard shortcuts, is this for a change within Thunderbird? Or locale based?
- Can you define a little more about "Thunderbird standards" re TransVision?

These types of nuggets will be very helpful going forward and I would like to capture them in the documentation and examples in the works now for transitioning.

**Comment by ovari** [comment]
1. The "New local folder" had a keyboard shortcut that was the same as the "Add Feed Account..."
2. "New local folder" should be in "New Locale Folder…" (Capitals and 1-character ellipsis)
3. Languages like Chinese, Japanese, Korean (CJK) seem to keep the shortcut of the en-US locale
image

TransVision has all the strings used every locale in Mozilla products.

**Comment by cleidigh** [comment]
@ovari 
I assume it was a typo and you meant "New Local Folder..."  NOT Locale ?
I will look at transvision to learn more.

**Comment by ovari** [comment]
Yes, it was a typo. Should be corrected. Can you merge?

**Comment by ovari** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices

**Comment by cleidigh** [comment]
@ovari 
I see nothing so far preventing me from doing so. I do want to build and test.  Assuming no problems I should be able to merge tomorrow.

**Comment by ovari** [comment]
Can you provide an xpi file so we can also test before it is released?

**Comment by ovari** [comment]
Should the add-on be renamed to from "LocalFolder" to "Local Folders", i.e. a space " " and plural? The translation would be very easy then.
https://transvision.mozfr.org/?recherche=Local+Folders&repo=gecko_strings&sourcelocale=en-US&locale=fr&search_type=strings&entire_string=entire_string

**Comment by cleidigh** [comment]
Sure .
I will probably create a merge branch just to have a clean workflow.  As you see, you have the honor of the first PR so you have to bear with me as I'm going for consistency in workflow.  I will post the XPI soon as I have it tomorrow and will wait for your thumbs-up before post it to ATN.

**Comment by ovari** [comment]
Looking at the [image above](https://user-images.githubusercontent.com/17465872/54875060-86a53b00-4e4b-11e9-90be-4ee5d5c5f16d.png), should "New Local Folder…" be "Add Local Folder…"?

**Comment by cleidigh** [comment]
@ovari 
One other question:  I actually went back-and-forth on the repository name capitalization.  I think LocalFolder is better, I guess I could rename it keeping an old link .  I am just wondering about bad affects of changing the name.  I guess since it is so new it should not be a problem.

**Comment by cleidigh** [comment]
@ovari 
In English, "Local Folders", plural, does make more sense.  I have to look at the ramifications of changing the name.  I cannot change the ID , but maybe that name change is okay.  Perhaps I merge the changes secondarily look at the name change which would take a lot more changes as well.

**Comment by cleidigh** [comment]
New versus Add
Either are grammatically fine, but if you look at Windows, the file Explorer action is "New Folder..."

**Comment by cleidigh** [comment]
Ovari

It would be great to better understand your role in the Thunderbird
universe.  I'm on a data collecting mission.

Christopher

**Comment by ovari** [comment]
### New/Add
For "New" vs "Add", yes Windows and Microsoft have their own terminology. [Microsoft International Terminology](https://www.microsoft.com/language). Mozilla is a cross-platform application, which does cater for differences in platforms. However, for consistency in the drop-down (which showed as a drop-up), "Add" for the en-US locale seems more appropriate.

### We don't have a role in the TB universe
- We've commented many times on tb-planning list, but unfortunately they don't pass moderation.
- Provided a few little suggestions, not code, for a few add-ons. Some add-on developers have implemented the suggestions, while other suggestions are not known how to implement like [view contacts as business cards](https://gitlab.com/CardBook/CardBook/issues/363), @cardbook developer's response https://gitlab.com/CardBook/CardBook/issues/363#note_109156620.
- Would be nice to have Thunderbird have a native Contacts module, like the [CardBook add-on](https://gitlab.com/CardBook/CardBook/), which could help many people migrate from Outlook.
- Would be nice if Thunderbird had a Address Book import from Outlook, like Thunderbird has for emails.

### Featured extensions
Local Folders should be included in [Featured Extensions](https://addons.thunderbird.net/extensions/?sort=featured). What do you think?

### Mail Merge add-on support
Your add-on has a very good use-case with the [Mail Merge add-on](https://addons.thunderbird.net/addon/mail-merge/) with IMAP accounts which are offline when creating emails. Not sure what [Alexander Bergmann](https://addons.thunderbird.net/en-US/thunderbird/user/tempuser/) GitHub handle is.

**Comment by ovari** [comment]
Below are some naming conventions used for the [Cardbook](https://addons.thunderbird.net/addon/cardbook/) and [Owl for Exchange](https://addons.thunderbird.net/addon/owl-for-exchange/) [add-ons](https://addons.thunderbird.net/) respectively.

Επαφές (CardBook) https://addons.thunderbird.net/el/addon/cardbook/
Névjegyzék (CardBook) https://addons.thunderbird.net/hu/addon/cardbook/
Kontak (CardBook) https://addons.thunderbird.net/id/addon/cardbook/
連絡先「CardBook」 https://addons.thunderbird.net/ja/addon/cardbook/
연락처 (CardBook) https://addons.thunderbird.net/ko/addon/cardbook/
Contacte (CardBook) https://addons.thunderbird.net/ro/addon/cardbook/
Kontakter (CardBook) https://addons.thunderbird.net/sv-SE/addon/cardbook/
Контакти «CardBook» https://addons.thunderbird.net/uk/addon/cardbook/

Eule für Exchange https://addons.thunderbird.net/de/addon/owl-for-exchange/
Owl for Exchange https://addons.thunderbird.net/en-US/addon/owl-for-exchange/
Aluco de Exchange https://addons.thunderbird.net/es/addon/owl-for-exchange/
Chouette pour Exchange https://addons.thunderbird.net/fr/addon/owl-for-exchange/
Bagoly az Exchange számára https://addons.thunderbird.net/hu/addon/owl-for-exchange/
Gufo per Exchange https://addons.thunderbird.net/it/addon/owl-for-exchange/
Exchange用のフクロウ https://addons.thunderbird.net/ja/addon/owl-for-exchange/
Uil voor Exchange https://addons.thunderbird.net/nl/addon/owl-for-exchange/
Sowa dla Exchange https://addons.thunderbird.net/pl/addon/owl-for-exchange/
Coruja para Exchange https://addons.thunderbird.net/pt-PT/addon/owl-for-exchange/
Сова для Exchange https://addons.thunderbird.net/ru/addon/owl-for-exchange/

Hope this helps in your _data collection mission_.

**Comment by cleidigh** [comment]
@ovari 
I got confirmation changing the name of the add-on should not be a problem.  I am going to change it to "LocalFolders"  I purposely do not want a space, the single word is almost brands like.

Give me a heads up when you're done tweaking the translations and I should be able to get an XPi to you today.  I will probably also do a couple more tweaks subsequently before uploading, also changing the icon.

**Comment by ovari** [comment]
This is a heads up to kindly ask you to get the XPI file ready. Any changes we think of we tend to do promptly. As more ideas come to mind then they are provided. Hope this makes sense. Thank you

**Comment by cleidigh** [comment]
@ovari 
I'm pulling your changes now.  I will do some quick testing and post a beta branch.  After I also have my own changes, I will target a release tomorrow if possible.  For reference I am on EST  in Providence

**Comment by ovari** [comment]
Thank you

**Comment by cleidigh** [comment]
FYI  I have to chase a silent failure, something is amiss

**Comment by cleidigh** [comment]
you cannot have more than one creator, the trick is to use developer.name but I'm going to do that later
Initial testing looks good
Pull Down the branch Hungarian locale

**Comment by ovari** [comment]
Can you add the xpi file here? We are doing everything through the web-browser. Thank you

**Comment by cleidigh** [comment]
yours is not the active branch
you can grab it from the web with the following link which comes out of the branch off the master repository
https://github.com/cleidigh/Localfolder-TB/tree/Hungarian-locale/xpi

**Comment by ovari** [comment]
Thanks, xpi file looks fine. Can this pull request be closed? Small changes are at https://github.com/cleidigh/Localfolder-TB/pull/8.

**Pull request closed without merging**
