### PR TITLE
pt-BR translation

### PR DESCRIPTION
**Pull request by anselmobd**
Here is my first and small contribution to your project.
The translation into Brazilian Portuguese.

### CODE REVIEW

**Comment by cleidigh** [comment]
@anselmobd 
Mointo brigado !
my apologies , my notifications did not get to me on this.  I just saw it today.
I am just about to post v2.0.0 with enhancements and important bug fixes.
I will add your translation , thanks much for the effort!  BTW I wish my Portuguese
was as good as my Spanish, I have a soft spot for Brazil (and a prior relationship from Rio ;-)

**Comment by anselmobd** [comment]
"Muito obrigado, digo eu!"
I hope your Portuguese is not a parameter of good fluency. :))
I'm glad to be able to contribute! I really enjoyed your project.
Who knows, one day we toast with a cold beer in Rio.

**Comment by cleidigh** [comment]
@anselmobd 
Awesome !
Brama Chope on the beaches of Ipanema, would love to be able to do it again ;-)

**Comment by cleidigh** [comment]
@anselmobd 
I am currently working as the Thunderbird extension liaison.  We are always looking for new people to contribute.  If you are interested in working on extensions let me know!
Thanks again for the localization.
Christopher

**Pull request merged**
