### PR TITLE
small changes

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by cleidigh** [comment]
@ovari 
I will merge it locally since I have to make other changes.  I may post a repository update tonight, but I want to get the other stuff before upgrading on ATN.

**Comment by ovari** [comment]
1. Can we delete our fork?
2. Do you plan to update the screenshots on ATN?
Please advise when you are ready for the ATN hu translations of Title, Description, Image captions, etc.
https://addons.thunderbird.net/hu/addon/localfolder/

Thank you

**Comment by cleidigh** [comment]
I have everything I need, you can delete your fork.
I did see the screenshots are old, but updated graphics are slow for me, I'm disabled, so I'm not rushing into that.

I will keep you posted .

**Comment by ovari** [comment]
Thanks

**Pull request closed without merging**
