### PR TITLE
Account and transvision.mozfr.org

### PR DESCRIPTION
**Pull request by ovari**
Account Name:
https://transvision.mozfr.org/?recherche=Account+Name%3A&repo=gecko_strings&sourcelocale=en-US&locale=zh-CN&search_type=strings&case_sensitive=case_sensitive&entire_string=entire_string

Local directory:
https://transvision.mozfr.org/?recherche=Local+directory%3A&repo=gecko_strings&sourcelocale=en-US&locale=zh-CN&search_type=strings&entire_string=entire_string

Account Settings
https://transvision.mozfr.org/?recherche=Account+Settings&repo=gecko_strings&sourcelocale=en-US&locale=zh-CN&search_type=strings&entire_string=entire_string

Select folder
https://transvision.mozfr.org/?recherche=Select+folder&repo=gecko_strings&sourcelocale=en-US&locale=zh-CN&search_type=strings&entire_string=entire_string

Browse…
https://transvision.mozfr.org/?recherche=Browse%E2%80%A6&repo=gecko_strings&sourcelocale=en-US&locale=zh-CN&search_type=strings&entire_string=entire_string

### CODE REVIEW

**Comment by ovari** [comment]
@cleidigh it would be appreciated if you could please advise when you have merged this pull request so we can delete our fork. Thank you

**Comment by cleidigh** [comment]
@ovari 
I have to look through the changes, however, have to say I do not think changing to "Folder Account"
it's what I would like to do.  I realize this is the category the folders are added, but they are not accounts and I don't like to coerce it that way.  Going forward I will look at what changes can be made to support this slightly differently.

If the other changes are tweaks, I will include them.

**Comment by ovari** [comment]
The default Thunderbird "Local Folders" is a special account. Please see image below.

image

Thank you

**Comment by cleidigh** [comment]
I do understand, but UI  adding the new folder under the account manager
presents it as a folder, even if it's under special account.  I do not
think using the "account language" anywhere but necessary is my opinion.
it is my hope that we can change the way Thunderbird presents these in the
future, but for now it should be a folder not a contorted account.

**Pull request closed without merging**
